openapi: 3.0.1
info:
  title: test2
  description: ''
  version: '1.0'
servers:
  - url: https://apim-lboropeza.azure-api.net/apiprueba
paths:
  /recurso:
    get:
      summary: getRecurso
      operationId: getrecurso
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]